add_test( [==[nd_array - Construction]==] /home/runner/work/nd_array/nd_array/_codeql_build_dir/nd_array_tests [==[nd_array - Construction]==]  )
set_tests_properties( [==[nd_array - Construction]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/nd_array/nd_array/_codeql_build_dir)
add_test( [==[nd_array - Element access]==] /home/runner/work/nd_array/nd_array/_codeql_build_dir/nd_array_tests [==[nd_array - Element access]==]  )
set_tests_properties( [==[nd_array - Element access]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/nd_array/nd_array/_codeql_build_dir)
add_test( [==[nd_array - Copy semantics]==] /home/runner/work/nd_array/nd_array/_codeql_build_dir/nd_array_tests [==[nd_array - Copy semantics]==]  )
set_tests_properties( [==[nd_array - Copy semantics]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/nd_array/nd_array/_codeql_build_dir)
add_test( [==[nd_array - Move semantics]==] /home/runner/work/nd_array/nd_array/_codeql_build_dir/nd_array_tests [==[nd_array - Move semantics]==]  )
set_tests_properties( [==[nd_array - Move semantics]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/nd_array/nd_array/_codeql_build_dir)
add_test( [==[nd_array - Operations]==] /home/runner/work/nd_array/nd_array/_codeql_build_dir/nd_array_tests [==[nd_array - Operations]==]  )
set_tests_properties( [==[nd_array - Operations]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/nd_array/nd_array/_codeql_build_dir)
add_test( [==[nd_array - Subspan]==] /home/runner/work/nd_array/nd_array/_codeql_build_dir/nd_array_tests [==[nd_array - Subspan]==]  )
set_tests_properties( [==[nd_array - Subspan]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/nd_array/nd_array/_codeql_build_dir)
add_test( [==[nd_array - Slice]==] /home/runner/work/nd_array/nd_array/_codeql_build_dir/nd_array_tests [==[nd_array - Slice]==]  )
set_tests_properties( [==[nd_array - Slice]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/nd_array/nd_array/_codeql_build_dir)
add_test( [==[nd_array - Properties]==] /home/runner/work/nd_array/nd_array/_codeql_build_dir/nd_array_tests [==[nd_array - Properties]==]  )
set_tests_properties( [==[nd_array - Properties]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/nd_array/nd_array/_codeql_build_dir)
add_test( [==[nd_array - Shape transforms]==] /home/runner/work/nd_array/nd_array/_codeql_build_dir/nd_array_tests [==[nd_array - Shape transforms]==]  )
set_tests_properties( [==[nd_array - Shape transforms]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/nd_array/nd_array/_codeql_build_dir)
add_test( [==[nd_array - Iterators and extents]==] /home/runner/work/nd_array/nd_array/_codeql_build_dir/nd_array_tests [==[nd_array - Iterators and extents]==]  )
set_tests_properties( [==[nd_array - Iterators and extents]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/nd_array/nd_array/_codeql_build_dir)
add_test( [==[nd_array - Span to array]==] /home/runner/work/nd_array/nd_array/_codeql_build_dir/nd_array_tests [==[nd_array - Span to array]==]  )
set_tests_properties( [==[nd_array - Span to array]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/nd_array/nd_array/_codeql_build_dir)
add_test( [==[nd_array - Array to span]==] /home/runner/work/nd_array/nd_array/_codeql_build_dir/nd_array_tests [==[nd_array - Array to span]==]  )
set_tests_properties( [==[nd_array - Array to span]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/nd_array/nd_array/_codeql_build_dir)
add_test( [==[nd_span - Construction]==] /home/runner/work/nd_array/nd_array/_codeql_build_dir/nd_array_tests [==[nd_span - Construction]==]  )
set_tests_properties( [==[nd_span - Construction]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/nd_array/nd_array/_codeql_build_dir)
add_test( [==[nd_span - Element access]==] /home/runner/work/nd_array/nd_array/_codeql_build_dir/nd_array_tests [==[nd_span - Element access]==]  )
set_tests_properties( [==[nd_span - Element access]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/nd_array/nd_array/_codeql_build_dir)
add_test( [==[nd_span - Const access]==] /home/runner/work/nd_array/nd_array/_codeql_build_dir/nd_array_tests [==[nd_span - Const access]==]  )
set_tests_properties( [==[nd_span - Const access]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/nd_array/nd_array/_codeql_build_dir)
add_test( [==[nd_span - Subspan]==] /home/runner/work/nd_array/nd_array/_codeql_build_dir/nd_array_tests [==[nd_span - Subspan]==]  )
set_tests_properties( [==[nd_span - Subspan]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/nd_array/nd_array/_codeql_build_dir)
add_test( [==[nd_span - Slice]==] /home/runner/work/nd_array/nd_array/_codeql_build_dir/nd_array_tests [==[nd_span - Slice]==]  )
set_tests_properties( [==[nd_span - Slice]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/nd_array/nd_array/_codeql_build_dir)
add_test( [==[nd_span - Properties]==] /home/runner/work/nd_array/nd_array/_codeql_build_dir/nd_array_tests [==[nd_span - Properties]==]  )
set_tests_properties( [==[nd_span - Properties]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/nd_array/nd_array/_codeql_build_dir)
add_test( [==[nd_span - Shape transforms]==] /home/runner/work/nd_array/nd_array/_codeql_build_dir/nd_array_tests [==[nd_span - Shape transforms]==]  )
set_tests_properties( [==[nd_span - Shape transforms]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/nd_array/nd_array/_codeql_build_dir)
add_test( [==[nd_span - Iterators and extents]==] /home/runner/work/nd_array/nd_array/_codeql_build_dir/nd_array_tests [==[nd_span - Iterators and extents]==]  )
set_tests_properties( [==[nd_span - Iterators and extents]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/nd_array/nd_array/_codeql_build_dir)
add_test( [==[nd_span - C-array interop]==] /home/runner/work/nd_array/nd_array/_codeql_build_dir/nd_array_tests [==[nd_span - C-array interop]==]  )
set_tests_properties( [==[nd_span - C-array interop]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/nd_array/nd_array/_codeql_build_dir)
add_test( [==[nd_span - Integration with nd_array]==] /home/runner/work/nd_array/nd_array/_codeql_build_dir/nd_array_tests [==[nd_span - Integration with nd_array]==]  )
set_tests_properties( [==[nd_span - Integration with nd_array]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/nd_array/nd_array/_codeql_build_dir)
add_test( [==[nd_span - Stride-aware iteration]==] /home/runner/work/nd_array/nd_array/_codeql_build_dir/nd_array_tests [==[nd_span - Stride-aware iteration]==]  )
set_tests_properties( [==[nd_span - Stride-aware iteration]==] PROPERTIES WORKING_DIRECTORY /home/runner/work/nd_array/nd_array/_codeql_build_dir)
set( nd_array_tests_TESTS [==[nd_array - Construction]==] [==[nd_array - Element access]==] [==[nd_array - Copy semantics]==] [==[nd_array - Move semantics]==] [==[nd_array - Operations]==] [==[nd_array - Subspan]==] [==[nd_array - Slice]==] [==[nd_array - Properties]==] [==[nd_array - Shape transforms]==] [==[nd_array - Iterators and extents]==] [==[nd_array - Span to array]==] [==[nd_array - Array to span]==] [==[nd_span - Construction]==] [==[nd_span - Element access]==] [==[nd_span - Const access]==] [==[nd_span - Subspan]==] [==[nd_span - Slice]==] [==[nd_span - Properties]==] [==[nd_span - Shape transforms]==] [==[nd_span - Iterators and extents]==] [==[nd_span - C-array interop]==] [==[nd_span - Integration with nd_array]==] [==[nd_span - Stride-aware iteration]==])
